version: '3.8'

services:
  symfony_app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "9999:9999"
    volumes:
      - ./api:/var/www/api