version: '3.8'

services:
  jyotish_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "9393:9393"
    volumes:
      - ./api:/var/www/api